### ISSUE TITLE
Art nonprofit career resources

### ISSUE THREAD

**Issue by artstie** [bensheldon/island94-middleman#11]
Dear Ben,

Have enjoyed reading your articles on salary negotiation and working at nonprofits. Our blog has a few resources that I hope you'll find useful:

Salary Negotiation in the Arts http://www.artstie.com/art-careers-guide/art-career-101/salary-negotiation-arts-part-1/

We also have an upcoming piece on pay in arts nonprofits.

Welcome your comments on any of the articles and feel free to share any resources that you think we should reference!

**Comment by bensheldon** [comment]
@artsie thanks for the details. Much appreciated!
